// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV3YBmgBnW5RVs-KUOT6Kdc9sM_pcTctM',
    appId: '1:923868162061:web:c09d7c5269c662f831cd44',
    messagingSenderId: '923868162061',
    projectId: 'tceworkmanagement',
    authDomain: 'tceworkmanagement.firebaseapp.com',
    storageBucket: 'tceworkmanagement.appspot.com',
    measurementId: 'G-26WC2QRGES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChvKtjNbKXx9eNazHOh2-FOMTXi0a9j2E',
    appId: '1:923868162061:android:362c3d2e56bfa02931cd44',
    messagingSenderId: '923868162061',
    projectId: 'tceworkmanagement',
    storageBucket: 'tceworkmanagement.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwaMpNZPIP15-lt5B-VuiBl3xlxSEMsbE',
    appId: '1:923868162061:ios:eba5d1ed45c89d6a31cd44',
    messagingSenderId: '923868162061',
    projectId: 'tceworkmanagement',
    storageBucket: 'tceworkmanagement.appspot.com',
    iosBundleId: 'com.tce.workManagementApp',
  );
}
